apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foo-pvc
  namespace: default
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: foo-pv
  accessModes:
    - ReadWriteOnce
    #- ReadWriteMany
    #- ReadOnlyMany
    #- ReadWriteOncePod
  resources:
    requests:
      storage: 256Mi