apiVersion: v1
kind: Pod
metadata:
  name: foo-pod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/hostfolder"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: foo-pvc