apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: "azuredisk"
  accessModes:
    - ReadWriteOnce
    #- ReadWriteMany
    #- ReadOnlyMany
    #- ReadWriteOncePod
  resources:
    requests:
      storage: 2Gi