apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azuredisk
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: managed
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate