apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    owner: shikki
spec:
  imagePullSecrets:
    - name: none
  restartPolicy: Never
  initContainers:
  - name: init-namespace
    image: busybox:1.28
    command: ['sh', '-c', 'if [ "shikki" == $(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace) ]; then echo "we are in the right namespace"; else echo "this is not the right namespace"; sleep 3600; fi ']
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  volumes: []



